services:
  postgres:
    image: postgres:16
    container_name: finverse-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finverse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8
    container_name: finverse-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8
    container_name: finverse-redis
    restart: always
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: finverse-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api-gateway:
    build:
      context: ./backend/api-gateway/nginx
    container_name: finverse-api-gateway
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - mongodb
      - redis
      - kafka

volumes:
  postgres_data:
  mongo_data:

# services:
#   postgres:
#     image: postgres:16
#     container_name: finverse-postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: finverse
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   mongodb:
#     image: mongo:8
#     container_name: finverse-mongodb
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

#   redis:
#     image: redis:8
#     container_name: finverse-redis
#     restart: always
#     ports:
#       - "6379:6379"

#   kafka:
#     image: apache/kafka:latest
#     container_name: finverse-kafka
#     restart: always
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: broker,controller
#       KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# volumes:
#   postgres_data:
#   mongo_data:
