services:
  postgres:
    image: postgres:16
    container_name: finverse-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finverse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8
    container_name: finverse-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8
    container_name: finverse-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data:
